version: "3"
services:

  apache2php:
    image: antonylevchenko/ui_task_4:apache-php
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/anton.levchenko/Projects/University/ui/UI_task_4_docker"

  nginx:
    image: antonylevchenko/ui_task_4:nginx
    ports:
      - "80:80"
    volumes:
      - "C:/Users/anton.levchenko/Projects/University/ui/UI_task_4_docker"
      
  mongo:
    image: antonylevchenko/ui_task_4:mongo
    ports: 
      - "27017:27017"